### PR TITLE
Metadata Web Application version 1.0

### PR DESCRIPTION
**Pull request by IfyAniefuna**
Both Metadata Applications output the same information on the Generic as well as the ALE sheets given the same input.
https://pastebin.com/njEzyMQd (Current Public Metadata Application Output)
https://pastebin.com/zFwWzPxL (New MetaData Application Output)

Bug fixed: Date on Public Metadata application incorrect. This was fixed in the new implementation to remain the same as the input data unless manually updated.

Serial number field added to New Metadata sheet in order to track individual samples

Read files field added to provide information on the individual reads per sample
Read-files field is a required on the ALE form

Removed ALE Specific drag and drop because it is not necessary anymore when compared with the Spreadsheet specific drag and drop

ALE Fields and Read-files are required in ALE form Spreadsheet Specific drag and drop

New Metadata sheet includes editing function. New functionality can drag and drop multiple metadata sheets. Edit multiple sheets at a time by editing the form below with the updated information and downloading. Any information that was not changed in the form will remain unique for each Metadata sheet.

Spreadsheet optional download- can download template add information and drag and drop to download multiple metadata sheets
https://pastebin.com/hzyzdkry (LINK TO Spreadsheet Specific Drag and Drop Sample Input CSV)
https://pastebin.com/KGCzLaEF (LINK TO Spreadsheet Specific Drag and Drop Sample Output CSV)

SBRG Blue added to panel headings on New Metadata application for style.

Instructions added to New Metadata application for clarification purposes.

### CODE REVIEW

**Comment by zakandrewking** [comment]
Looking good. Just a couple small things:

Can you provide a description of "Serial Number" on the page? Is this something that we should have for every experiment?

It would be good to group all the required attributes at the top (i.e. move "serial number" and "read files" down below the required info)

@IfyAniefuna @pvphaneuf

**Comment by IfyAniefuna** [comment]
No It is not required and read files is only required on the ALE workflow.

> Looking good. Just a couple small things:
>
> Can you provide a description of "Serial Number" on the page? Is this
> something that we should have for every experiment?
>
> It would be good to group all the required attributes at the top (i.e.
> move "serial number" and "read files" down below the required info)
>
> @IfyAniefuna @pvphaneuf
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/SBRG/experiment_metadata/pull/23#issuecomment-325743763


Ify.Aniefuna

**Comment by pvphaneuf** [comment]
@IfyAniefuna 
For the serial number description, please rewrite what is currently within the instructions at the top of the webapp to describe that the serial number is to be used in mapping this metadata form to other externally maintained metadata, such as that of the wetlab. Could say "Add a serial number if appropriate to map this metadata to externally maintained metadata."

**Comment by pvphaneuf** [comment]
@IfyAniefuna 
Within the metadata webapp GUI, move "Base Media" and "Isolate Type" under "Strain description" to accomplish the grouping of required types.

**Pull request merged**
